name             'df_box_jenkins'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures df_box_jenkins'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.4'

depends 'df_java'
depends 'df_jenkins'
depends 'df_ruby'
depends 'df_maven'
depends 'df_virtualbox'
depends 'df_vagrant'
depends 'df_test-kitchen'
depends 'df_git'
depends 'df_chefdk'